name: cora
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - dask
  - intake
  - xarray
  - intake-xarray
  - holoviews
  - geoviews
  - hvplot
  - bokeh
  - datashader
  - cartopy
  - jupyter
  - jupyter_bokeh
  - s3fs
  - folium
  - branca
  - zarr=2.18
  - pip:
      - cmocean
      - geopy